/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.profesores;

import gui.inisioSesion.PantallaDatos;
import factory.DaoFactory;
import interfazDao.IDao;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import models.Profesor;

/**
 *
 * @author estudiante
 */
public class ModificarProfesores extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProfesores
     */
    public ModificarProfesores(Profesor profe) {
        initComponents();
        this.setLocationRelativeTo(null);
        setLabelImage();
        jLabelId.setText(String.valueOf(profe.getId()));
        jTextFieldDni.setText(profe.getDni());
        jTextFieldNombre.setText(profe.getNombre());
        jTextFieldApellido.setText(profe.getApellido());
        jTextFieldNacimiento.setText(profe.getNacimiento());
        jTextFieldCodPostal.setText(String.valueOf(profe.getCod_postal()));
        jTextFieldTelefono.setText(String.valueOf(profe.getTelefono()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNacimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodPostal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelBack = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel1.setText("DATOS NUEVO PROFESOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 180, 20);

        jButtonUpdate.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate);
        jButtonUpdate.setBounds(190, 330, 110, 30);

        jPanel2.setLayout(new java.awt.GridLayout(7, 2));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2);
        jPanel2.add(jLabelId);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel3.setText("DNI:");
        jPanel2.add(jLabel3);
        jPanel2.add(jTextFieldDni);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel4.setText("NOMBRE: ");
        jPanel2.add(jLabel4);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNombre);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel5.setText("APELLIDO:");
        jPanel2.add(jLabel5);
        jPanel2.add(jTextFieldApellido);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel6.setText("FECHA NACIMIENTO:");
        jPanel2.add(jLabel6);
        jPanel2.add(jTextFieldNacimiento);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel7.setText("CODIGO POSTAL:");
        jPanel2.add(jLabel7);
        jPanel2.add(jTextFieldCodPostal);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel8.setText("TELEFONO");
        jPanel2.add(jLabel8);
        jPanel2.add(jTextFieldTelefono);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(63, 47, 380, 250);

        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelBack);
        jLabelBack.setBounds(10, 10, 30, 30);
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        int id;
        String dni;
        String nombre;
        String apellido;
        String nacimiento;
        int cod_postal;
        int telefono;

        id= Integer.parseInt(jLabelId.getText());
        dni = jTextFieldDni.getText();
        nombre = jTextFieldNombre.getText();
        apellido = jTextFieldApellido.getText();
        nacimiento = jTextFieldNacimiento.getText();
        cod_postal = Integer.parseInt(jTextFieldCodPostal.getText());
        telefono = Integer.parseInt(jTextFieldTelefono.getText());
        Profesor profesor = new Profesor(id, dni, nombre, apellido, nacimiento, cod_postal, telefono);
        try {
            IDao dao = DaoFactory.getDao(DaoFactory.DaoType.PROFESOR);
            dao.updateRecord(profesor, id);
            PantallaDatos pD = new PantallaDatos ("profesores");
            pD.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ModificarProfesores.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        PantallaDatos pD;
        try {
            pD = new PantallaDatos("profesores");
            pD.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ModificarProfesores.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void setLabelImage() {
        String currentDir = System.getProperty("user.dir");
        String imagePath = currentDir + "/src/img/fondo-form.jpg";
        String imagePath4 = currentDir + "/src/img/flecha-izquierda.png";
        
        jPanel2.setBackground(new Color(221, 221, 221, 0));
           
        Image imag1 = Toolkit.getDefaultToolkit().createImage(imagePath);
        imag1 = imag1.getScaledInstance(jLabelFondo.getWidth(), jLabelFondo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img2 = new ImageIcon(imag1);
        jLabelFondo.setIcon(img2);
        
        Image imag4 = Toolkit.getDefaultToolkit().createImage(imagePath4);
        imag4 = imag4.getScaledInstance(jLabelBack.getWidth(), jLabelBack.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img5 = new ImageIcon(imag4);
        jLabelBack.setIcon(img5);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCodPostal;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNacimiento;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
