/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.inisioSesion;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author rolan
 */
public class Diagrama extends javax.swing.JFrame {

    /**
     * Creates new form Diagrama
     */
    public Diagrama() {
        initComponents();
        this.setLocationRelativeTo(null);
        setLabelImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExit = new javax.swing.JLabel();
        jLabelDiagrama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit);
        jLabelExit.setBounds(750, 520, 30, 30);
        getContentPane().add(jLabelDiagrama);
        jLabelDiagrama.setBounds(10, 0, 780, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void setLabelImage() {
        String currentDir = System.getProperty("user.dir");
        String imagePath = currentDir + "/src/img/Entidad-Relacion.jpg";
        String imagePath2 = currentDir + "/src/img/cerrar-sesion.png";
                             
        Image imag1 = Toolkit.getDefaultToolkit().createImage(imagePath);
        imag1 = imag1.getScaledInstance(jLabelDiagrama.getWidth(), jLabelDiagrama.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img2 = new ImageIcon(imag1);
        jLabelDiagrama.setIcon(img2);
        
        Image imag2 = Toolkit.getDefaultToolkit().createImage(imagePath2);
        imag2 = imag2.getScaledInstance(jLabelExit.getWidth(), jLabelExit.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img3 = new ImageIcon(imag2);
        jLabelExit.setIcon(img3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDiagrama;
    private javax.swing.JLabel jLabelExit;
    // End of variables declaration//GEN-END:variables
}
