/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.inisioSesion;

import crearTablas.CrearTablas;
import factory.DaoFactory;
import factory.DbFactory;
import java.sql.SQLException;
import interfazDao.IDao;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Usuario;

/**
 *
 * @author rolan
 */
public class Loggin extends javax.swing.JFrame {

    /**
     * Creates new form Loggin
     */
    public Loggin()  {
        initComponents();
        this.setLocationRelativeTo(null);
        setLabelImage();
        List <Usuario> usuarios = new ArrayList();
       
        try {
            CrearTablas tablasH2 = DbFactory.getFactory("H2");
            tablasH2.crearTablas();
            IDao dao = DaoFactory.getDao(DaoFactory.DaoType.USUARIO);
            usuarios = dao.readRecords();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger (Loggin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if (usuarios.isEmpty()) {
            
            try {
                IDao dao = DaoFactory.getDao(DaoFactory.DaoType.USUARIO);
                Usuario user1 = new Usuario (1,"JAVIER", "CASTEJON");
                Usuario user2 = new Usuario (2,"ROLANDO", "TOMALO");
                Usuario user3 = new Usuario (3,"ITACA", "ITACA");
                dao.createRecord(user1);
                dao.createRecord(user2);
                dao.createRecord(user3);
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger (Loggin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("USUARIO: ");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldUser);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CONTRASEÑA:");
        jPanel1.add(jLabel4);
        jPanel1.add(jPasswordFieldPass);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 248, 330, 80));

        jButtonLogin.setBackground(new java.awt.Color(2, 132, 54));
        jButtonLogin.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setText("INICIAR");
        jButtonLogin.setAutoscrolls(true);
        jButtonLogin.setBorder(null);
        jButtonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 110, 30));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INICIO SESIÓN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 190, 60));
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 50));

        jLabelInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 30, 30));

        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 30, 30));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String nombre;
        String password;
        boolean encontrado = false;
        
        nombre = jTextFieldUser.getText();
        password = jPasswordFieldPass.getText();
        
        List <Usuario> usuarios = new ArrayList();
        
        
        try {
            IDao dao = DaoFactory.getDao(DaoFactory.DaoType.USUARIO);
            usuarios = dao.readRecords();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger (Loggin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Usuario user : usuarios) {
            if (nombre.equals(user.getNombre())) {
                encontrado = true;
                if (!password.equals(user.getPassword())) {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "", JOptionPane.ERROR_MESSAGE);
                } else {
                    PantallaEntidades pE = new PantallaEntidades();
                    pE.setVisible(true);
                    dispose();
                }    
            }    
        }
        
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario no registrado", "", JOptionPane.ERROR_MESSAGE);
        }                        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabelInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseClicked
        
        JOptionPane.showMessageDialog(this, "Rellenar los campos con mayúsculas", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelInfoMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked
    
    private void setLabelImage() {
        String currentDir = System.getProperty("user.dir");
        String imagePath = currentDir + "/src/img/HomeItaca.jpg";
        String imagePath2 = currentDir + "/src/img/LogoItaca.png";
        String imagePath3 = currentDir + "/src/img/cerrar-sesion.png";
        String imagePath4 = currentDir + "/src/img/boton-de-informacion.png";
        
        jPanel1.setBackground(new Color(221, 221, 221, 0));
           
        Image imag1 = Toolkit.getDefaultToolkit().createImage(imagePath);
        imag1 = imag1.getScaledInstance(jLabelFondo.getWidth(), jLabelFondo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img2 = new ImageIcon(imag1);
        jLabelFondo.setIcon(img2);
        
        Image imag2 = Toolkit.getDefaultToolkit().createImage(imagePath2);
        imag2 = imag2.getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img3 = new ImageIcon(imag2);
        jLabelLogo.setIcon(img3);
        
        Image imag3 = Toolkit.getDefaultToolkit().createImage(imagePath3);
        imag3 = imag3.getScaledInstance(jLabelExit.getWidth(), jLabelExit.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img4 = new ImageIcon(imag3);
        jLabelExit.setIcon(img4);
        
        Image imag4 = Toolkit.getDefaultToolkit().createImage(imagePath4);
        imag4 = imag4.getScaledInstance(jLabelInfo.getWidth(), jLabelInfo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img5 = new ImageIcon(imag4);
        jLabelInfo.setIcon(img5);
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
